unclog: unclog_global.c File Reference
unclog_global.c File Reference
#include "unclog_int.h"
#include <ini.h>
Functions
void unclog_global_configure (unclog_global_t *global, const char *config, int usefile, int initialized)
unclog_global_t * unclog_global_create (const char *config, int usefile, int initialized)
void unclog_global_destroy (unclog_global_t *global)
void unclog_global_dump_config (unclog_global_t *global)
void unclog_global_sink_add (unclog_global_t *global, unclog_sink_t *sink)
void unclog_global_sink_clear (unclog_global_t *global, int include_registered)
unclog_sink_t * unclog_global_sink_get (unclog_global_t *global, const char *sink)
void unclog_global_source_add (unclog_global_t *global, unclog_source_t *source)
unclog_source_t * unclog_global_source_get (unclog_global_t *global, const char *source)
int unclog_global_source_remove (unclog_global_t *global, unclog_source_t *source)
Function Documentation
void unclog_global_configure (unclog_global_t * global, const char * config, int usefile, int initialized)
Definition at line 34 of file unclog_global.c.
References unclog_global_s::defaults, unclog_sink_s::i, unclog_sink_methods_s::init, unclog_global_s::initialized, unclog_source_s::level, unclog_values_s::level, unclog_sink_internal_s::methods, unclog_source_s::next, unclog_sink_internal_s::next, unclog_keyvalue_s::next, unclog_sink_s::settings, unclog_global_s::sinks, unclog_global_s::sinks_defined, unclog_global_s::sources, unclog_defaults, unclog_global_sink_add(), unclog_keyvalue_destroy(), unclog_sink_create(), and unclog_sink_s::values.
{
     memcpy(&global->defaults, &unclog_defaults, sizeof(unclog_values_t));
     global->sinks_defined = 0;
     global->initialized = initialized;
     for (unclog_sink_t* s = global->sinks; s != NULL; s = s->i->next) {
         memcpy(&s->settings, &unclog_defaults, sizeof(unclog_values_t));
         for (unclog_keyvalue_t* k = s->values; k != NULL; k = k->next) {
             unclog_keyvalue_destroy(k);
         }
     }
     for (unclog_source_t* s = global->sources; s != NULL; s = s->next) {
         s->level = unclog_defaults.level;
     }
     if (usefile == 1) {
         const char** f = unclog_ini_files;
         for (; *f != NULL; f++) {
             if (access(*f, R_OK) != 0) continue;
             ini_parse(*f, unclog_ini_handler, global);
             break;
         }
     } else {
         if (config != NULL) {
             ini_parse_string(config, unclog_ini_handler, global);
         }
     }
     if (global->sinks_defined == 0) {
         unclog_sink_t* s = unclog_sink_create(&global->defaults, "stderr");
         unclog_global_sink_add(global, s);
     }
     for (unclog_sink_t* s = global->sinks; s != NULL; s = s->i->next) {
         if (s->i->methods.init != NULL) s->i->methods.init(s);
     }
 }
unclog_global_t* unclog_global_create (const char * config, int usefile, int initialized)
Definition at line 72 of file unclog_global.c.
{
     unclog_global_t* g = malloc(sizeof(unclog_global_t));
     memset(g, 0, sizeof(unclog_global_t));
     unclog_global_configure(g, config, usefile, initialized);
     return g;
 }
void unclog_global_destroy (unclog_global_t * global)
Definition at line 101 of file unclog_global.c.
References unclog_source_s::next, unclog_global_s::sources, unclog_global_sink_clear(), and unclog_source_destroy().
{
     unclog_global_sink_clear(global, 1);
     unclog_source_t* source = global->sources;
     while (source != NULL) {
         unclog_source_t* d = source;
         source = source->next;
         unclog_source_destroy(d);
     }
     free(global);
 }
void unclog_global_dump_config (unclog_global_t * global)
Definition at line 9 of file unclog_global.c.
References unclog_global_s::defaults, unclog_values_s::details, unclog_sink_s::i, unclog_keyvalue_s::key, unclog_source_s::level, unclog_values_s::level, unclog_source_s::next, unclog_sink_internal_s::next, unclog_keyvalue_s::next, unclog_sink_s::settings, unclog_sink_internal_s::sink, unclog_global_s::sinks, unclog_source_s::source, unclog_global_s::sources, unclog_details_tostr(), unclog_level_tostr(), unclog_keyvalue_s::value, and unclog_sink_s::values.
{
     fprintf(stderr, "global->defaults.level: %s\n", unclog_level_tostr(global->defaults.level));
     char* detailsstr = unclog_details_tostr(global->defaults.details);
     fprintf(stderr, "global->defaults.details: %s\n", detailsstr);
     free(detailsstr);
     unclog_source_t* source = global->sources;
     for (; source != NULL; source = source->next) {
         fprintf(stderr, "global->source[%s].level: %s\n", source->source,
                 unclog_level_tostr(source->level));
     }
     unclog_sink_t* sink = global->sinks;
     for (; sink != NULL; sink = sink->i->next) {
         fprintf(stderr, "global->sink[%s].level: %s\n", sink->i->sink,
                 unclog_level_tostr(sink->settings.level));
         detailsstr = unclog_details_tostr(sink->settings.details);
         fprintf(stderr, "global->sink[%s].details: %04X | %s\n", sink->i->sink,
                 sink->settings.details, detailsstr);
         free(detailsstr);
         unclog_keyvalue_t* kv = sink->values;
         for (; kv != NULL; kv = kv->next) {
             fprintf(stderr, "global->sink[%s].%s: %s\n", sink->i->sink, kv->key, kv->value);
         }
     }
 }
void unclog_global_sink_add (unclog_global_t * global, unclog_sink_t * sink)
Definition at line 151 of file unclog_global.c.
References unclog_sink_s::i, unclog_sink_internal_s::next, and unclog_global_s::sinks.
{
     sink->i->next = global->sinks;
     global->sinks = sink;
 }
void unclog_global_sink_clear (unclog_global_t * global, int include_registered)
Definition at line 80 of file unclog_global.c.
References unclog_sink_s::i, unclog_sink_internal_s::next, unclog_sink_internal_s::registered, unclog_global_s::sinks, and unclog_sink_destroy().
{
     unclog_sink_t* s = global->sinks;
     unclog_sink_t* p = NULL;
     while (s != NULL) {
         if (s->i->registered == 0 || include_registered) {
             if (p == NULL) {
                 global->sinks = s->i->next;
             } else {
                 p->i->next = s->i->next;
             }
             unclog_sink_t* d = s;
             s = s->i->next;
             unclog_sink_destroy(d);
         } else {
             p = s;
             s = s->i->next;
         }
     }
 }
unclog_sink_t* unclog_global_sink_get (unclog_global_t * global, const char * sink)
Definition at line 156 of file unclog_global.c.
References unclog_sink_s::i, unclog_sink_internal_s::next, unclog_sink_internal_s::sink, and unclog_global_s::sinks.
{
     unclog_sink_t* s = global->sinks;
     for (; s != NULL; s = s->i->next) {
         if (strcmp(s->i->sink, sink) == 0) return s;
     }
     return NULL;
 }
void unclog_global_source_add (unclog_global_t * global, unclog_source_t * source)
Definition at line 114 of file unclog_global.c.
References unclog_source_s::next, and unclog_global_s::sources.
{
     source->next = global->sources;
     global->sources = source;
 }
unclog_source_t* unclog_global_source_get (unclog_global_t * global, const char * source)
Definition at line 119 of file unclog_global.c.
References unclog_source_s::next, unclog_source_s::source, and unclog_global_s::sources.
{
     unclog_source_t* s = global->sources;
     for (; s != NULL; s = s->next) {
         if (strcmp(s->source, source) == 0) return s;
     }
     return NULL;
 }
int unclog_global_source_remove (unclog_global_t * global, unclog_source_t * source)
Definition at line 127 of file unclog_global.c.
References unclog_source_s::active, unclog_source_s::next, unclog_global_s::sources, and unclog_source_destroy().
{
     int has_active_handles = 0;
     unclog_source_t* s = global->sources;
     unclog_source_t* p = NULL;
     while (s != NULL) {
         if (s == source) {
             if (p == NULL) {
                 global->sources = s->next;
             } else {
                 p->next = s->next;
             }
             unclog_source_t* d = s;
             s = s->next;
             unclog_source_destroy(d);
         } else {
             if (s->active == 1) has_active_handles = 1;
             p = s;
             s = s->next;
         }
     }
     return has_active_handles;
 }