unclog: unclog_int.h File Reference
unclog_int.h File Reference
#include "unclog/unclog_adv.h"
#include <linux/limits.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct unclog_details_s
struct unclog_global_s
struct unclog_levels_s
struct unclog_sink_internal_s
struct unclog_source_s
Typedefs
typedef struct unclog_details_s unclog_details_t
typedef struct unclog_global_s unclog_global_t
typedef struct unclog_levels_s unclog_levels_t
typedef struct unclog_source_s unclog_source_t
Functions
uint32_t unclog_details_todetail (const char *value)
char * unclog_details_tostr (uint32_t details)
void unclog_global_configure (unclog_global_t *global, const char *config, int usefile, int initialized)
unclog_global_t * unclog_global_create (const char *config, int usefile, int initialized)
void unclog_global_destroy (unclog_global_t *global)
void unclog_global_dump_config (unclog_global_t *global)
void unclog_global_sink_add (unclog_global_t *global, unclog_sink_t *source)
void unclog_global_sink_clear (unclog_global_t *global, int include_registered)
unclog_sink_t * unclog_global_sink_get (unclog_global_t *global, const char *sink)
void unclog_global_source_add (unclog_global_t *global, unclog_source_t *source)
unclog_source_t * unclog_global_source_get (unclog_global_t *global, const char *source)
int unclog_global_source_remove (unclog_global_t *global, unclog_source_t *source)
int unclog_ini_handler (void *data, const char *section, const char *name, const char *value)
unclog_keyvalue_t * unclog_keyvalue_create (const char *key, const char *value)
void unclog_keyvalue_destroy (unclog_keyvalue_t *v)
char * unclog_keyvalue_get (unclog_keyvalue_t *v, const char *key)
char unclog_level_tochar (int level)
int unclog_level_tolevel (const char *value)
const char * unclog_level_tostr (int level)
void unclog_sink_add_keyvalue (unclog_sink_t *sink, const char *key, const char *value)
unclog_sink_t * unclog_sink_create (unclog_values_t *settings, const char *name)
void unclog_sink_destroy (unclog_sink_t *sink)
uint64_t unclog_sink_stderr_get_num_messages ()
unclog_source_t * unclog_source_create (int level, const char *name)
void unclog_source_destroy (unclog_source_t *source)
Variables
const unclog_values_t unclog_defaults
const char * unclog_defaults_file
unclog_details_t unclog_details []
unclog_global_t * unclog_global
unclog_levels_t unclog_levels []
Typedef Documentation
typedef struct unclog_details_s unclog_details_t
typedef struct unclog_global_s unclog_global_t
typedef struct unclog_levels_s unclog_levels_t
typedef struct unclog_source_s unclog_source_t
Function Documentation
uint32_t unclog_details_todetail (const char * value)
Definition at line 54 of file unclog_levels.c.
References unclog_details_s::detail, unclog_details_s::name, and unclog_details.
{
     for (unclog_details_t* d = unclog_details; d->name != NULL; d++) {
         if (strcmp(d->name, value) == 0) {
             return d->detail;
         }
     }
     return 0;
 }
char* unclog_details_tostr (uint32_t details)
Definition at line 63 of file unclog_levels.c.
References unclog_details_s::detail, unclog_details_s::name, and unclog_details.
{
     char* retval = malloc(4096);
     memset(retval, 0, 4096);
     char* buffer = retval;
     int next = 0;
     unclog_details_t* d = unclog_details;
     for (; d->name != NULL; d++) {
         if (!(d->detail & details)) continue;
         if (next != 0) buffer += sprintf(buffer, ",");
         next = 1;
         buffer += sprintf(buffer, "%s", d->name);
     }
     return retval;
 }
void unclog_global_configure (unclog_global_t * global, const char * config, int usefile, int initialized)
Definition at line 34 of file unclog_global.c.
References unclog_global_s::defaults, unclog_sink_s::i, unclog_sink_methods_s::init, unclog_global_s::initialized, unclog_source_s::level, unclog_values_s::level, unclog_sink_internal_s::methods, unclog_source_s::next, unclog_sink_internal_s::next, unclog_keyvalue_s::next, unclog_sink_s::settings, unclog_global_s::sinks, unclog_global_s::sinks_defined, unclog_global_s::sources, unclog_defaults, unclog_global_sink_add(), unclog_keyvalue_destroy(), unclog_sink_create(), and unclog_sink_s::values.
{
     memcpy(&global->defaults, &unclog_defaults, sizeof(unclog_values_t));
     global->sinks_defined = 0;
     global->initialized = initialized;
     for (unclog_sink_t* s = global->sinks; s != NULL; s = s->i->next) {
         memcpy(&s->settings, &unclog_defaults, sizeof(unclog_values_t));
         for (unclog_keyvalue_t* k = s->values; k != NULL; k = k->next) {
             unclog_keyvalue_destroy(k);
         }
     }
     for (unclog_source_t* s = global->sources; s != NULL; s = s->next) {
         s->level = unclog_defaults.level;
     }
     if (usefile == 1) {
         const char** f = unclog_ini_files;
         for (; *f != NULL; f++) {
             if (access(*f, R_OK) != 0) continue;
             ini_parse(*f, unclog_ini_handler, global);
             break;
         }
     } else {
         if (config != NULL) {
             ini_parse_string(config, unclog_ini_handler, global);
         }
     }
     if (global->sinks_defined == 0) {
         unclog_sink_t* s = unclog_sink_create(&global->defaults, "stderr");
         unclog_global_sink_add(global, s);
     }
     for (unclog_sink_t* s = global->sinks; s != NULL; s = s->i->next) {
         if (s->i->methods.init != NULL) s->i->methods.init(s);
     }
 }
unclog_global_t* unclog_global_create (const char * config, int usefile, int initialized)
Definition at line 72 of file unclog_global.c.
{
     unclog_global_t* g = malloc(sizeof(unclog_global_t));
     memset(g, 0, sizeof(unclog_global_t));
     unclog_global_configure(g, config, usefile, initialized);
     return g;
 }
void unclog_global_destroy (unclog_global_t * global)
Definition at line 101 of file unclog_global.c.
References unclog_source_s::next, unclog_global_s::sources, unclog_global_sink_clear(), and unclog_source_destroy().
{
     unclog_global_sink_clear(global, 1);
     unclog_source_t* source = global->sources;
     while (source != NULL) {
         unclog_source_t* d = source;
         source = source->next;
         unclog_source_destroy(d);
     }
     free(global);
 }
void unclog_global_dump_config (unclog_global_t * global)
Definition at line 9 of file unclog_global.c.
References unclog_global_s::defaults, unclog_values_s::details, unclog_sink_s::i, unclog_keyvalue_s::key, unclog_source_s::level, unclog_values_s::level, unclog_source_s::next, unclog_sink_internal_s::next, unclog_keyvalue_s::next, unclog_sink_s::settings, unclog_sink_internal_s::sink, unclog_global_s::sinks, unclog_source_s::source, unclog_global_s::sources, unclog_details_tostr(), unclog_level_tostr(), unclog_keyvalue_s::value, and unclog_sink_s::values.
{
     fprintf(stderr, "global->defaults.level: %s\n", unclog_level_tostr(global->defaults.level));
     char* detailsstr = unclog_details_tostr(global->defaults.details);
     fprintf(stderr, "global->defaults.details: %s\n", detailsstr);
     free(detailsstr);
     unclog_source_t* source = global->sources;
     for (; source != NULL; source = source->next) {
         fprintf(stderr, "global->source[%s].level: %s\n", source->source,
                 unclog_level_tostr(source->level));
     }
     unclog_sink_t* sink = global->sinks;
     for (; sink != NULL; sink = sink->i->next) {
         fprintf(stderr, "global->sink[%s].level: %s\n", sink->i->sink,
                 unclog_level_tostr(sink->settings.level));
         detailsstr = unclog_details_tostr(sink->settings.details);
         fprintf(stderr, "global->sink[%s].details: %04X | %s\n", sink->i->sink,
                 sink->settings.details, detailsstr);
         free(detailsstr);
         unclog_keyvalue_t* kv = sink->values;
         for (; kv != NULL; kv = kv->next) {
             fprintf(stderr, "global->sink[%s].%s: %s\n", sink->i->sink, kv->key, kv->value);
         }
     }
 }
void unclog_global_sink_add (unclog_global_t * global, unclog_sink_t * source)
Definition at line 151 of file unclog_global.c.
References unclog_sink_s::i, unclog_sink_internal_s::next, and unclog_global_s::sinks.
{
     sink->i->next = global->sinks;
     global->sinks = sink;
 }
void unclog_global_sink_clear (unclog_global_t * global, int include_registered)
Definition at line 80 of file unclog_global.c.
References unclog_sink_s::i, unclog_sink_internal_s::next, unclog_sink_internal_s::registered, unclog_global_s::sinks, and unclog_sink_destroy().
{
     unclog_sink_t* s = global->sinks;
     unclog_sink_t* p = NULL;
     while (s != NULL) {
         if (s->i->registered == 0 || include_registered) {
             if (p == NULL) {
                 global->sinks = s->i->next;
             } else {
                 p->i->next = s->i->next;
             }
             unclog_sink_t* d = s;
             s = s->i->next;
             unclog_sink_destroy(d);
         } else {
             p = s;
             s = s->i->next;
         }
     }
 }
unclog_sink_t* unclog_global_sink_get (unclog_global_t * global, const char * sink)
Definition at line 156 of file unclog_global.c.
References unclog_sink_s::i, unclog_sink_internal_s::next, unclog_sink_internal_s::sink, and unclog_global_s::sinks.
{
     unclog_sink_t* s = global->sinks;
     for (; s != NULL; s = s->i->next) {
         if (strcmp(s->i->sink, sink) == 0) return s;
     }
     return NULL;
 }
void unclog_global_source_add (unclog_global_t * global, unclog_source_t * source)
Definition at line 114 of file unclog_global.c.
References unclog_source_s::next, and unclog_global_s::sources.
{
     source->next = global->sources;
     global->sources = source;
 }
unclog_source_t* unclog_global_source_get (unclog_global_t * global, const char * source)
Definition at line 119 of file unclog_global.c.
References unclog_source_s::next, unclog_source_s::source, and unclog_global_s::sources.
{
     unclog_source_t* s = global->sources;
     for (; s != NULL; s = s->next) {
         if (strcmp(s->source, source) == 0) return s;
     }
     return NULL;
 }
int unclog_global_source_remove (unclog_global_t * global, unclog_source_t * source)
Definition at line 127 of file unclog_global.c.
References unclog_source_s::active, unclog_source_s::next, unclog_global_s::sources, and unclog_source_destroy().
{
     int has_active_handles = 0;
     unclog_source_t* s = global->sources;
     unclog_source_t* p = NULL;
     while (s != NULL) {
         if (s == source) {
             if (p == NULL) {
                 global->sources = s->next;
             } else {
                 p->next = s->next;
             }
             unclog_source_t* d = s;
             s = s->next;
             unclog_source_destroy(d);
         } else {
             if (s->active == 1) has_active_handles = 1;
             p = s;
             s = s->next;
         }
     }
     return has_active_handles;
 }
int unclog_ini_handler (void * data, const char * section, const char * name, const char * value)
Definition at line 53 of file unclog_config.c.
References unclog_source_s::level, unclog_sink_s::settings, unclog_level_tolevel(), and unclog_sink_add_keyvalue().
{
     unclog_global_t* global = data;
     // fprintf(stderr, "%s.%s: %s\n", section, name, value);
     if (MATCH(section, "Defaults")) {
         unclog_defaults_handler(global, name, value);
         return 0;
     }
     if (global->sinks_defined == 0) {
         unclog_defaults_handler(global, "Sinks", "stderr");
     }
     unclog_sink_t* sink = unclog_global_sink_get(global, section);
     if (sink != NULL) {
         if (!unclog_common_handler(&sink->settings, name, value))
             unclog_sink_add_keyvalue(sink, name, value);
         return 0;
     }
     unclog_source_t* source = unclog_global_source_get(global, section);
     if (source == NULL) {
         source = unclog_source_create(global->defaults.level, section);
         source->initialized = global->initialized;
         unclog_global_source_add(global, source);
     }
     if (MATCH(name, "Level")) {
         source->level = unclog_level_tolevel(value);
     }
     return 0;
 }
unclog_keyvalue_t* unclog_keyvalue_create (const char * key, const char * value)
Definition at line 150 of file unclog_sink.c.
{
     unclog_keyvalue_t* kv = malloc(sizeof(unclog_keyvalue_t));
     kv->key = strdup(key);
     kv->value = strdup(value);
     return kv;
 }
void unclog_keyvalue_destroy (unclog_keyvalue_t * v)
Definition at line 158 of file unclog_sink.c.
References unclog_keyvalue_s::key, and unclog_keyvalue_s::value.
{
     free(v->key);
     free(v->value);
     free(v);
 }
char* unclog_keyvalue_get (unclog_keyvalue_t * v, const char * key)
Definition at line 164 of file unclog_sink.c.
References unclog_keyvalue_s::key, and unclog_keyvalue_s::value.
{
     while (v != NULL) {
         if (strcmp(v->key, key) == 0) {
             return v->value;
         }
     }
     return NULL;
 }
char unclog_level_tochar (int level)
Definition at line 36 of file unclog_levels.c.
References unclog_levels_s::level, unclog_levels_s::name, unclog_levels_s::shortname, and unclog_levels.
{
     for (unclog_levels_t* l = unclog_levels; l->name != NULL; l++) {
         if (UNCLOG_LEVEL_COMPARE(level, l->level)) {
             return l->shortname;
         }
     }
     return 'M';
 }
int unclog_level_tolevel (const char * value)
Definition at line 27 of file unclog_levels.c.
References unclog_values_s::level, unclog_levels_s::level, unclog_levels_s::name, unclog_defaults, and unclog_levels.
{
     for (unclog_levels_t* l = unclog_levels; l->name != NULL; l++) {
         if (strcmp(l->name, value) == 0) {
             return l->level;
         }
     }
     return unclog_defaults.level;
 }
const char* unclog_level_tostr (int level)
Definition at line 45 of file unclog_levels.c.
References unclog_levels_s::level, unclog_levels_s::name, and unclog_levels.
{
     for (unclog_levels_t* l = unclog_levels; l->name != NULL; l++) {
         if (UNCLOG_LEVEL_COMPARE(level, l->level)) {
             return l->name;
         }
     }
     return "Minimum";
 }
void unclog_sink_add_keyvalue (unclog_sink_t * sink, const char * key, const char * value)
Definition at line 173 of file unclog_sink.c.
References unclog_keyvalue_s::next, unclog_keyvalue_create(), and unclog_sink_s::values.
{
     unclog_keyvalue_t* kv = unclog_keyvalue_create(key, value);
     kv->next = sink->values;
     sink->values = kv;
 }
unclog_sink_t* unclog_sink_create (unclog_values_t * settings, const char * name)
Definition at line 128 of file unclog_sink.c.
References unclog_sink_list_s::name.
{
     unclog_sink_t* handle = malloc(sizeof(unclog_sink_t));
     memset(handle, 0, sizeof(unclog_sink_t));
     handle->i = malloc(sizeof(unclog_sink_internal_t));
     memset(handle->i, 0, sizeof(unclog_sink_internal_t));
     if (settings != NULL)
         memcpy(&handle->settings, settings, sizeof(unclog_values_t));
     else
         memcpy(&handle->settings, &unclog_global->defaults, sizeof(unclog_values_t));
     handle->i->sink = strdup(name);
     unclog_sink_list_t* l = unclog_default_sinks;
     for (; l->name != NULL; l++) {
         if (strcmp(l->name, name) == 0) {
             handle->i->methods = l->methods;
         }
     }
     return handle;
 }
void unclog_sink_destroy (unclog_sink_t * sink)
Definition at line 180 of file unclog_sink.c.
References unclog_sink_methods_s::deinit, unclog_sink_s::i, unclog_sink_internal_s::methods, unclog_keyvalue_s::next, unclog_sink_internal_s::sink, unclog_keyvalue_destroy(), and unclog_sink_s::values.
{
     if (sink->i->methods.deinit != NULL) sink->i->methods.deinit(sink);
     unclog_keyvalue_t* kv = sink->values;
     while (kv != NULL) {
         unclog_keyvalue_t* d = kv;
         kv = kv->next;
         unclog_keyvalue_destroy(d);
     }
     free(sink->i->sink);
     free(sink->i);
     free(sink);
 }
uint64_t unclog_sink_stderr_get_num_messages ()
Definition at line 84 of file unclog_sink.c.
References unclog_global, and unclog_global_sink_get().
{
     unclog_sink_t* s = unclog_global_sink_get(unclog_global, "stderr");
     unclog_sink_stderr_data_t* d = s->data;
     return d->messages;
 }
unclog_source_t* unclog_source_create (int level, const char * name)
Definition at line 5 of file unclog_source.c.
{
     unclog_source_t* handle = malloc(sizeof(unclog_source_t));
     memset(handle, 0, sizeof(unclog_source_t));
     handle->source = strdup(source);
     handle->level = level;
     return handle;
 }
void unclog_source_destroy (unclog_source_t * source)
Definition at line 15 of file unclog_source.c.
References unclog_source_s::source.
{
     free(source->source);
     free(source);
 }
Variable Documentation
const unclog_values_t unclog_defaults
Definition at line 5 of file unclog.c.
const char* unclog_defaults_file
Definition at line 9 of file unclog.c.
unclog_details_t unclog_details[]
Definition at line 16 of file unclog_levels.c.
unclog_global_t* unclog_global
Definition at line 12 of file unclog.c.
unclog_levels_t unclog_levels[]
Definition at line 4 of file unclog_levels.c.