unclog: unclog.h File Reference
unclog.h File Reference
#include <limits.h>
#include <time.h>
Data Structures
struct unclog_data_s
struct unclog_s
Macros
#define _POSIX_C_SOURCE 199309L
#define UL_CR(ha,...) UNCLOG((ha), UNCLOG_LEVEL_CRITICAL, ##__VA_ARGS__);
#define UL_DE(ha,...) UNCLOG((ha), UNCLOG_LEVEL_DEBUG, ##__VA_ARGS__);
#define UL_ER(ha,...) UNCLOG((ha), UNCLOG_LEVEL_ERROR, ##__VA_ARGS__);
#define UL_FA(ha,...) UNCLOG((ha), UNCLOG_LEVEL_FATAL, ##__VA_ARGS__);
#define UL_IN(ha,...) UNCLOG((ha), UNCLOG_LEVEL_INFO, ##__VA_ARGS__);
#define UL_TR(ha,...) UNCLOG((ha), UNCLOG_LEVEL_TRACE, ##__VA_ARGS__);
#define UL_WA(ha,...) UNCLOG((ha), UNCLOG_LEVEL_WARNING, ##__VA_ARGS__);
#define UNCLOG(h, l,...)
#define UNCLOG_LEVEL_COMPARE(l, m) ((l) <= (m))
#define UNCLOG_LEVEL_CRITICAL 400
#define UNCLOG_LEVEL_CUTOFF UNCLOG_LEVEL_MINIMUM
#define UNCLOG_LEVEL_DEBUG 1200
#define UNCLOG_LEVEL_ERROR 600
#define UNCLOG_LEVEL_FATAL 200
#define UNCLOG_LEVEL_INFO 1000
#define UNCLOG_LEVEL_MAXIMUM 0
#define UNCLOG_LEVEL_MINIMUM INT_MAX
#define UNCLOG_LEVEL_TRACE 1400
#define UNCLOG_LEVEL_WARNING 800
Typedefs
typedef struct unclog_data_s unclog_data_t
typedef struct unclog_s unclog_t
Functions
void unclog_close (unclog_t *handle)
void unclog_log (unclog_data_t data,...)
unclog_t * unclog_open (const char *source)
Macro Definition Documentation
#define _POSIX_C_SOURCE 199309L
Definition at line 4 of file unclog.h.
#define UL_CR (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_CRITICAL, ##__VA_ARGS__);
Definition at line 58 of file unclog.h.
#define UL_DE (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_DEBUG, ##__VA_ARGS__);
Definition at line 62 of file unclog.h.
#define UL_ER (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_ERROR, ##__VA_ARGS__);
Definition at line 59 of file unclog.h.
#define UL_FA (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_FATAL, ##__VA_ARGS__);
Definition at line 57 of file unclog.h.
#define UL_IN (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_INFO, ##__VA_ARGS__);
Definition at line 61 of file unclog.h.
#define UL_TR (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_TRACE, ##__VA_ARGS__);
Definition at line 63 of file unclog.h.
#define UL_WA (ha, ...) UNCLOG((ha), UNCLOG_LEVEL_WARNING, ##__VA_ARGS__);
Definition at line 60 of file unclog.h.
#define UNCLOG (h, l, ...)
Value:
{                                                                                      \
        if (UNCLOG_LEVEL_COMPARE(l, UNCLOG_LEVEL_CUTOFF) && ((h) != NULL) &&               \
            UNCLOG_LEVEL_COMPARE(l, (h)->level)) {                                         \
            unclog_log(                                                                    \
                (unclog_data_t){                                                           \
                    .ha = (h), .le = (l), .fi = __FILE__, .fu = __func__, .li = __LINE__}, \
                ##__VA_ARGS__);                                                            \
        }                                                                                  \
    }
Definition at line 46 of file unclog.h.
#define UNCLOG_LEVEL_COMPARE (l, m) ((l) <= (m))
Definition at line 23 of file unclog.h.
#define UNCLOG_LEVEL_CRITICAL 400
Definition at line 16 of file unclog.h.
#define UNCLOG_LEVEL_CUTOFF UNCLOG_LEVEL_MINIMUM
Definition at line 43 of file unclog.h.
#define UNCLOG_LEVEL_DEBUG 1200
Definition at line 20 of file unclog.h.
#define UNCLOG_LEVEL_ERROR 600
Definition at line 17 of file unclog.h.
#define UNCLOG_LEVEL_FATAL 200
Definition at line 15 of file unclog.h.
#define UNCLOG_LEVEL_INFO 1000
Definition at line 19 of file unclog.h.
#define UNCLOG_LEVEL_MAXIMUM 0
Definition at line 14 of file unclog.h.
#define UNCLOG_LEVEL_MINIMUM INT_MAX
Definition at line 22 of file unclog.h.
#define UNCLOG_LEVEL_TRACE 1400
Definition at line 21 of file unclog.h.
#define UNCLOG_LEVEL_WARNING 800
Definition at line 18 of file unclog.h.
Typedef Documentation
typedef struct unclog_data_s unclog_data_t
typedef struct unclog_s unclog_t
Function Documentation
void unclog_close (unclog_t * handle)
Definition at line 123 of file unclog.c.
References unclog_source_s::active, unclog_source_s::initialized, unclog_global_s::initialized, unclog_global, and unclog_global_source_remove().
{
     if (public_handle == NULL) return;
     unclog_source_t* handle = (unclog_source_t*)public_handle;
     pthread_rwlock_wrlock(&unclog_mutex);
     handle->active--;
     int has_active_handles;
     if (handle->active == 0 && handle->initialized == 0) {
         has_active_handles = unclog_global_source_remove(unclog_global, handle);
     } else {
         has_active_handles = 1;
     }
     if (!has_active_handles && unclog_global->initialized != 1) {
         unclog_deinit_nolock();
     }
     pthread_rwlock_unlock(&unclog_mutex);
 }
void unclog_log (unclog_data_t data, ...)
Definition at line 101 of file unclog.c.
References unclog_data_s::ha, unclog_sink_s::i, unclog_data_s::le, unclog_values_s::level, unclog_s::level, unclog_sink_methods_s::log, unclog_sink_internal_s::methods, unclog_sink_internal_s::next, unclog_data_s::no, unclog_sink_s::settings, unclog_data_s::si, unclog_global_s::sinks, and unclog_global.
{
     if (data.ha == NULL) return;
     if (!UNCLOG_LEVEL_COMPARE(data.le, data.ha->level)) return;
     clock_gettime(CLOCK_REALTIME, &data.no);
     pthread_rwlock_rdlock(&unclog_mutex);
     unclog_sink_t* sink = unclog_global->sinks;
     for (; sink != NULL; sink = sink->i->next) {
         if (sink->i->methods.log == NULL) continue;
         if (!UNCLOG_LEVEL_COMPARE(data.le, sink->settings.level)) continue;
         va_list al;
         va_start(al, data);
         data.si = sink;
         sink->i->methods.log(&data, al);
         va_end(al);
     }
     pthread_rwlock_unlock(&unclog_mutex);
 }
unclog_t* unclog_open (const char * source)
Definition at line 83 of file unclog.c.
References unclog_source_s::active, unclog_global_s::defaults, unclog_values_s::level, unclog_global, unclog_global_source_add(), unclog_global_source_get(), and unclog_source_create().
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_init_nolock(NULL, 1, 0);
     unclog_source_t* handle = unclog_global_source_get(unclog_global, source);
     if (handle == NULL) {
         handle = unclog_source_create(unclog_global->defaults.level, source);
         unclog_global_source_add(unclog_global, handle);
     }
     handle->active++;
     pthread_rwlock_unlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
     return (unclog_t*)handle;
 }