unclog: unclog_sink.c File Reference
unclog_sink.c File Reference
#include "unclog_int.h"
Data Structures
struct unclog_sink_file_data_s
struct unclog_sink_list_s
struct unclog_sink_stderr_data_s
Macros
#define _BSD_SOURCE
Typedefs
typedef struct
unclog_sink_file_data_s unclog_sink_file_data_t
typedef struct unclog_sink_list_s unclog_sink_list_t
typedef struct
unclog_sink_stderr_data_s unclog_sink_stderr_data_t
Functions
size_t stringappend (char *dest, const char *src)
unclog_keyvalue_t * unclog_keyvalue_create (const char *key, const char *value)
void unclog_keyvalue_destroy (unclog_keyvalue_t *v)
char * unclog_keyvalue_get (unclog_keyvalue_t *v, const char *key)
void unclog_sink_add_keyvalue (unclog_sink_t *sink, const char *key, const char *value)
unclog_sink_t * unclog_sink_create (unclog_values_t *settings, const char *name)
void unclog_sink_destroy (unclog_sink_t *sink)
uint64_t unclog_sink_stderr_get_num_messages ()
Macro Definition Documentation
#define _BSD_SOURCE
Definition at line 1 of file unclog_sink.c.
Typedef Documentation
typedef struct unclog_sink_file_data_s unclog_sink_file_data_t
typedef struct unclog_sink_list_s unclog_sink_list_t
typedef struct unclog_sink_stderr_data_s unclog_sink_stderr_data_t
Function Documentation
size_t stringappend (char * dest, const char * src)
Definition at line 5 of file unclog_sink.c.
{
     size_t size = strlen(src);
     memcpy(dest, src, size + 1);
     return size;
 }
unclog_keyvalue_t* unclog_keyvalue_create (const char * key, const char * value)
Definition at line 150 of file unclog_sink.c.
{
     unclog_keyvalue_t* kv = malloc(sizeof(unclog_keyvalue_t));
     kv->key = strdup(key);
     kv->value = strdup(value);
     return kv;
 }
void unclog_keyvalue_destroy (unclog_keyvalue_t * v)
Definition at line 158 of file unclog_sink.c.
References unclog_keyvalue_s::key, and unclog_keyvalue_s::value.
{
     free(v->key);
     free(v->value);
     free(v);
 }
char* unclog_keyvalue_get (unclog_keyvalue_t * v, const char * key)
Definition at line 164 of file unclog_sink.c.
References unclog_keyvalue_s::key, and unclog_keyvalue_s::value.
{
     while (v != NULL) {
         if (strcmp(v->key, key) == 0) {
             return v->value;
         }
     }
     return NULL;
 }
void unclog_sink_add_keyvalue (unclog_sink_t * sink, const char * key, const char * value)
Definition at line 173 of file unclog_sink.c.
References unclog_keyvalue_s::next, unclog_keyvalue_create(), and unclog_sink_s::values.
{
     unclog_keyvalue_t* kv = unclog_keyvalue_create(key, value);
     kv->next = sink->values;
     sink->values = kv;
 }
unclog_sink_t* unclog_sink_create (unclog_values_t * settings, const char * name)
Definition at line 128 of file unclog_sink.c.
References unclog_sink_list_s::name.
{
     unclog_sink_t* handle = malloc(sizeof(unclog_sink_t));
     memset(handle, 0, sizeof(unclog_sink_t));
     handle->i = malloc(sizeof(unclog_sink_internal_t));
     memset(handle->i, 0, sizeof(unclog_sink_internal_t));
     if (settings != NULL)
         memcpy(&handle->settings, settings, sizeof(unclog_values_t));
     else
         memcpy(&handle->settings, &unclog_global->defaults, sizeof(unclog_values_t));
     handle->i->sink = strdup(name);
     unclog_sink_list_t* l = unclog_default_sinks;
     for (; l->name != NULL; l++) {
         if (strcmp(l->name, name) == 0) {
             handle->i->methods = l->methods;
         }
     }
     return handle;
 }
void unclog_sink_destroy (unclog_sink_t * sink)
Definition at line 180 of file unclog_sink.c.
References unclog_sink_methods_s::deinit, unclog_sink_s::i, unclog_sink_internal_s::methods, unclog_keyvalue_s::next, unclog_sink_internal_s::sink, unclog_keyvalue_destroy(), and unclog_sink_s::values.
{
     if (sink->i->methods.deinit != NULL) sink->i->methods.deinit(sink);
     unclog_keyvalue_t* kv = sink->values;
     while (kv != NULL) {
         unclog_keyvalue_t* d = kv;
         kv = kv->next;
         unclog_keyvalue_destroy(d);
     }
     free(sink->i->sink);
     free(sink->i);
     free(sink);
 }
uint64_t unclog_sink_stderr_get_num_messages ()
Definition at line 84 of file unclog_sink.c.
References unclog_global, and unclog_global_sink_get().
{
     unclog_sink_t* s = unclog_global_sink_get(unclog_global, "stderr");
     unclog_sink_stderr_data_t* d = s->data;
     return d->messages;
 }