unclog: unclog_adv.h File Reference
unclog_adv.h File Reference
#include <unclog/unclog.h>
#include <stdarg.h>
#include <stdint.h>
Data Structures
struct unclog_keyvalue_s
struct unclog_sink_methods_s
struct unclog_sink_s
struct unclog_values_s
Macros
#define UNCLOG_OPT_FILE 0x08
#define UNCLOG_OPT_LEVEL 0x02
#define UNCLOG_OPT_LINE 0x10
#define UNCLOG_OPT_MAXIMUM 0x3F
#define UNCLOG_OPT_MESSAGE 0x20
#define UNCLOG_OPT_SOURCE 0x04
#define UNCLOG_OPT_TIMESTAMP 0x01
Typedefs
typedef struct unclog_keyvalue_s unclog_keyvalue_t
typedef void(* unclog_sink_deinit_t)(unclog_sink_t *sink)
typedef void(* unclog_sink_init_t)(unclog_sink_t *sink)
typedef struct
unclog_sink_internal_s unclog_sink_internal_t
typedef void(* unclog_sink_log_t)(unclog_data_t *d, va_list l)
typedef struct
unclog_sink_methods_s unclog_sink_methods_t
typedef struct unclog_sink_s unclog_sink_t
typedef struct unclog_values_s unclog_values_t
Functions
void unclog_deinit (void)
void unclog_init (const char *config)
void unclog_reinit (const char *config)
void unclog_sink_register (const char *name, unclog_values_t *settings, unclog_sink_methods_t methods)
Macro Definition Documentation
#define UNCLOG_OPT_FILE 0x08
Definition at line 15 of file unclog_adv.h.
#define UNCLOG_OPT_LEVEL 0x02
Definition at line 13 of file unclog_adv.h.
#define UNCLOG_OPT_LINE 0x10
Definition at line 16 of file unclog_adv.h.
#define UNCLOG_OPT_MAXIMUM 0x3F
Definition at line 18 of file unclog_adv.h.
#define UNCLOG_OPT_MESSAGE 0x20
Definition at line 17 of file unclog_adv.h.
#define UNCLOG_OPT_SOURCE 0x04
Definition at line 14 of file unclog_adv.h.
#define UNCLOG_OPT_TIMESTAMP 0x01
Definition at line 12 of file unclog_adv.h.
Typedef Documentation
typedef struct unclog_keyvalue_s unclog_keyvalue_t
typedef void(* unclog_sink_deinit_t)(unclog_sink_t *sink)
Definition at line 42 of file unclog_adv.h.
typedef void(* unclog_sink_init_t)(unclog_sink_t *sink)
Definition at line 40 of file unclog_adv.h.
typedef struct unclog_sink_internal_s unclog_sink_internal_t
Definition at line 31 of file unclog_adv.h.
typedef void(* unclog_sink_log_t)(unclog_data_t *d, va_list l)
Definition at line 41 of file unclog_adv.h.
typedef struct unclog_sink_methods_s unclog_sink_methods_t
typedef struct unclog_sink_s unclog_sink_t
typedef struct unclog_values_s unclog_values_t
Function Documentation
void unclog_deinit (void)
Definition at line 38 of file unclog.c.
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_deinit_nolock();
     pthread_rwlock_unlock(&unclog_mutex);
 }
void unclog_init (const char * config)
Definition at line 27 of file unclog.c.
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_deinit_nolock();
     unclog_init_nolock(config, 0, 1);
     pthread_rwlock_unlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
 }
void unclog_reinit (const char * config)
Definition at line 46 of file unclog.c.
References unclog_global, unclog_global_configure(), and unclog_global_sink_clear().
{
     pthread_rwlock_wrlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
     unclog_global_sink_clear(unclog_global, 0);
     unclog_global_configure(unclog_global, config, 0, 1);
     // unclog_global_dump_config(unclog_global);
     pthread_rwlock_unlock(&unclog_mutex);
 }
void unclog_sink_register (const char * name, unclog_values_t * settings, unclog_sink_methods_t methods)
Definition at line 57 of file unclog.c.
References unclog_global_s::defaults, unclog_values_s::details, unclog_sink_s::i, unclog_sink_methods_s::init, unclog_values_s::level, unclog_sink_internal_s::methods, unclog_sink_internal_s::registered, unclog_sink_s::settings, unclog_global, unclog_global_sink_add(), unclog_global_sink_get(), and unclog_sink_create().
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_sink_t* sink = unclog_global_sink_get(unclog_global, name);
     if (sink == NULL) {
         sink = unclog_sink_create(settings, name);
         unclog_global_sink_add(unclog_global, sink);
     }
     if (settings != NULL) {
         memcpy(&sink->settings, settings, sizeof(unclog_values_t));
         if (settings->level == 0) sink->settings.level = unclog_global->defaults.level;
         if (settings->details == 0) sink->settings.details = unclog_global->defaults.details;
     }
     sink->i->methods = methods;
     sink->i->registered = 1;
     if (sink->i->methods.init != NULL) sink->i->methods.init(sink);
     pthread_rwlock_unlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
 }