unclog: unclog.c File Reference
unclog.c File Reference
#include "unclog_int.h"
Macros
#define _GNU_SOURCE
Functions
void unclog_close (unclog_t *public_handle)
void unclog_deinit (void)
void unclog_init (const char *config)
void unclog_log (unclog_data_t data,...)
unclog_t * unclog_open (const char *source)
void unclog_reinit (const char *config)
void unclog_sink_register (const char *name, unclog_values_t *settings, unclog_sink_methods_t methods)
Variables
const unclog_values_t unclog_defaults
const char * unclog_defaults_file = "unclog.log"
unclog_global_t * unclog_global = NULL
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 1 of file unclog.c.
Function Documentation
void unclog_close (unclog_t * public_handle)
Definition at line 123 of file unclog.c.
References unclog_source_s::active, unclog_source_s::initialized, unclog_global_s::initialized, unclog_global, and unclog_global_source_remove().
{
     if (public_handle == NULL) return;
     unclog_source_t* handle = (unclog_source_t*)public_handle;
     pthread_rwlock_wrlock(&unclog_mutex);
     handle->active--;
     int has_active_handles;
     if (handle->active == 0 && handle->initialized == 0) {
         has_active_handles = unclog_global_source_remove(unclog_global, handle);
     } else {
         has_active_handles = 1;
     }
     if (!has_active_handles && unclog_global->initialized != 1) {
         unclog_deinit_nolock();
     }
     pthread_rwlock_unlock(&unclog_mutex);
 }
void unclog_deinit (void)
Definition at line 38 of file unclog.c.
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_deinit_nolock();
     pthread_rwlock_unlock(&unclog_mutex);
 }
void unclog_init (const char * config)
Definition at line 27 of file unclog.c.
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_deinit_nolock();
     unclog_init_nolock(config, 0, 1);
     pthread_rwlock_unlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
 }
void unclog_log (unclog_data_t data, ...)
Definition at line 101 of file unclog.c.
References unclog_data_s::ha, unclog_sink_s::i, unclog_data_s::le, unclog_values_s::level, unclog_s::level, unclog_sink_methods_s::log, unclog_sink_internal_s::methods, unclog_sink_internal_s::next, unclog_data_s::no, unclog_sink_s::settings, unclog_data_s::si, unclog_global_s::sinks, and unclog_global.
{
     if (data.ha == NULL) return;
     if (!UNCLOG_LEVEL_COMPARE(data.le, data.ha->level)) return;
     clock_gettime(CLOCK_REALTIME, &data.no);
     pthread_rwlock_rdlock(&unclog_mutex);
     unclog_sink_t* sink = unclog_global->sinks;
     for (; sink != NULL; sink = sink->i->next) {
         if (sink->i->methods.log == NULL) continue;
         if (!UNCLOG_LEVEL_COMPARE(data.le, sink->settings.level)) continue;
         va_list al;
         va_start(al, data);
         data.si = sink;
         sink->i->methods.log(&data, al);
         va_end(al);
     }
     pthread_rwlock_unlock(&unclog_mutex);
 }
unclog_t* unclog_open (const char * source)
Definition at line 83 of file unclog.c.
References unclog_source_s::active, unclog_global_s::defaults, unclog_values_s::level, unclog_global, unclog_global_source_add(), unclog_global_source_get(), and unclog_source_create().
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_init_nolock(NULL, 1, 0);
     unclog_source_t* handle = unclog_global_source_get(unclog_global, source);
     if (handle == NULL) {
         handle = unclog_source_create(unclog_global->defaults.level, source);
         unclog_global_source_add(unclog_global, handle);
     }
     handle->active++;
     pthread_rwlock_unlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
     return (unclog_t*)handle;
 }
void unclog_reinit (const char * config)
Definition at line 46 of file unclog.c.
References unclog_global, unclog_global_configure(), and unclog_global_sink_clear().
{
     pthread_rwlock_wrlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
     unclog_global_sink_clear(unclog_global, 0);
     unclog_global_configure(unclog_global, config, 0, 1);
     // unclog_global_dump_config(unclog_global);
     pthread_rwlock_unlock(&unclog_mutex);
 }
void unclog_sink_register (const char * name, unclog_values_t * settings, unclog_sink_methods_t methods)
Definition at line 57 of file unclog.c.
References unclog_global_s::defaults, unclog_values_s::details, unclog_sink_s::i, unclog_sink_methods_s::init, unclog_values_s::level, unclog_sink_internal_s::methods, unclog_sink_internal_s::registered, unclog_sink_s::settings, unclog_global, unclog_global_sink_add(), unclog_global_sink_get(), and unclog_sink_create().
{
     pthread_rwlock_wrlock(&unclog_mutex);
     unclog_sink_t* sink = unclog_global_sink_get(unclog_global, name);
     if (sink == NULL) {
         sink = unclog_sink_create(settings, name);
         unclog_global_sink_add(unclog_global, sink);
     }
     if (settings != NULL) {
         memcpy(&sink->settings, settings, sizeof(unclog_values_t));
         if (settings->level == 0) sink->settings.level = unclog_global->defaults.level;
         if (settings->details == 0) sink->settings.details = unclog_global->defaults.details;
     }
     sink->i->methods = methods;
     sink->i->registered = 1;
     if (sink->i->methods.init != NULL) sink->i->methods.init(sink);
     pthread_rwlock_unlock(&unclog_mutex);
     // unclog_global_dump_config(unclog_global);
 }
Variable Documentation
const unclog_values_t unclog_defaults
Initial value:
= {
    .level = UNCLOG_LEVEL_WARNING,
    .details = (UNCLOG_OPT_TIMESTAMP | UNCLOG_OPT_LEVEL | UNCLOG_OPT_SOURCE | UNCLOG_OPT_MESSAGE),
}
Definition at line 5 of file unclog.c.
const char* unclog_defaults_file = "unclog.log"
Definition at line 9 of file unclog.c.
unclog_global_t* unclog_global = NULL
Definition at line 12 of file unclog.c.